### ISSUE TITLE
Issue with Dialga's Default Pose Tail.

### ISSUE THREAD

**Issue by Escope12** [bgsamm/pbr-models-import-export#1]
I found an issue where Dialga's tail is bent. Is this possible to fix this? 
![image](https://user-images.githubusercontent.com/8963276/130690934-a07bfac7-8826-4e15-bcab-e92ad319ce5e.png)

![image](https://user-images.githubusercontent.com/8963276/130690949-a42d70d0-7179-4c4d-aab3-f313a34e7a0c.png)

**Comment by bgsamm** [comment]
Correct pose should look like this I guess

![image](https://user-images.githubusercontent.com/8357867/130707743-4bde982f-4a4d-4f03-8451-a84d493db017.png)

but I have no idea what the issue is. Compared to the Dialga model from Brawl, which should supposedly be the same, the only difference is the position of the "tail_A" bone, but I double-checked the value being read from the .sdr and it seems correct.

**Comment by Escope12** [comment]
Will it be updated with the script?

**Comment by bgsamm** [comment]
Seems the kink in the tail is in fact correctly read from the SDR, just a weird quirk of the model
